SurfBoardWeb/Models/Board.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SurfBoardWeb.Models
{
    public class Board
    {
        
        public int BoardId { get; set; }

        [StringLength(60, MinimumLength = 5)]
        [Required]
        public string Name { get; set; }

        [DisplayName("Length (feet)")]
        [Range(0, 100)]
        [Required]
        public double Length { get; set; }

        [DisplayName("Width (inchs)")]
        [Range(0, 100)]
        [Required]
        public double Width { get; set; }

        [DisplayName("Thickness (Inches)")]
        [Range(0, 100)]
        [Required]
        public double Thickness { get; set; }

        [DisplayName("Volume (L)")]
        [Range(0, 100)]
        [Required]
        public double Volume { get; set; }


        [Required]
        public string Type { get; set; }

        [DataType(DataType.Currency)]
        [Required]
        public double Price{ get; set; } //bør laves til decimal

        [Timestamp]
        public byte[] RowVersion { get; set; }

        public string? Equipment { get; set; }
        public string? PicturePath { get; set; }

        public bool IsBooked { get; set; }
    }
}

SurfBoardWeb/Controllers/BoardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SurfBoardWeb.Data;
using SurfBoardWeb.Models;

namespace SurfBoardWeb.Controllers
{
	public class BoardsController : Controller
	{
		private readonly SurfBoardWebContext _context;
		private readonly UserManager<DefaultUser> _userManager;

		public BoardsController(SurfBoardWebContext context)
		{
			_context = context;
		}
		#region GET - Boards.. 
		// GET: Boards
		#region Filter Options
		public async Task<IActionResult> Index(string BoardType, string searchString, string sortOrder, string currentFilter, int? pageNumber)
		{
			ViewData["CurrentSort"] = sortOrder;


			ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
			ViewData["LengthSortParm"] = sortOrder == "Length" ? "length_desc" : "Length";
			ViewData["WidthSortParm"] = sortOrder == "Width" ? "width_desc" : "Width";
			ViewData["ThicknessSortParm"] = sortOrder == "Thickness" ? "thickness_desc" : "Thickness";
			ViewData["VolumeSortParm"] = sortOrder == "Volume" ? "volume_desc" : "Volume";
			ViewData["TypeSortParm"] = sortOrder == "Type" ? "type_desc" : "Type";
			ViewData["PriceSortParm"] = sortOrder == "Price" ? "price_desc" : "Price";
			ViewData["EquipmentSortParm"] = sortOrder == "Equipment" ? "equipment_desc" : "Equipment";
			ViewData["CurrentFilter"] = searchString;

			IQueryable<string> genreQuery = from m in _context.Board
											orderby m.Type
											select m.Type;

			IQueryable<Board> boards;

			if (User.Identity.IsAuthenticated)
			{
				boards = from m in _context.Board
						 select m;
			}
			else
			{
				boards = from m in _context.Board
						 where m.BoardId % 2 == 0
						 select m;
			}

			switch (sortOrder)
			{
				case "name_desc":
					boards = boards.OrderByDescending(m => m.Name);
					break;
				case "Length":
					boards = boards.OrderBy(m => m.Length);
					break;
				case "length_desc":
					boards = boards.OrderByDescending(m => m.Length);
					break;
				case "Width":
					boards = boards.OrderBy(m => m.Width);
					break;
				case "width_desc":
					boards = boards.OrderByDescending(m => m.Width);
					break;
				case "Thickness":
					boards = boards.OrderBy(m => m.Thickness);
					break;
				case "thickness_desc":
					boards = boards.OrderByDescending(m => m.Thickness);
					break;
				case "Volume":
					boards = boards.OrderBy(m => m.Volume);
					break;
				case "volume_desc":
					boards = boards.OrderByDescending(m => m.Volume);
					break;
				case "Type":
					boards = boards.OrderBy(m => m.Type);
					break;
				case "type_desc":
					boards = boards.OrderByDescending(m => m.Type);
					break;
				case "Price":
					boards = boards.OrderBy(m => m.Price);
					break;
				case "price_desc":
					boards = boards.OrderByDescending(m => m.Price);
					break;
				case "Equipment":
					boards = boards.OrderBy(m => m.Equipment);
					break;
				case "equipment_desc":
					boards = boards.OrderByDescending(m => m.Equipment);
					break;
				default:
					boards = boards.OrderBy(m => m.Name);
					break;
			}
			#endregion
		#region Search Options
			if (!string.IsNullOrEmpty(searchString))
			{
				boards = boards.Where(model => model.Name!.Contains(searchString)
						|| model.Equipment!.Contains(searchString)
						|| model.Type!.Contains(searchString));
			}
			#endregion
			if (!string.IsNullOrEmpty(BoardType))
			{
				boards = boards.Where(x => x.Type == BoardType);
			}

			if (searchString != null)
			{
				pageNumber = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			var BoardTypeVM = new BoardTypeViewModel
			{
				Types = new SelectList(await genreQuery.Distinct().ToListAsync()),
				Boards = await boards.ToListAsync()
			};

			int pageSize = 5;

			return View(await PaginatedList<Board>.CreateAsync(boards.AsNoTracking(), pageNumber ?? 1, pageSize));
		}
		#endregion
		// GET: Boards/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Board == null)
			{
				return NotFound();
			}

			var board = await _context.Board
				.FirstOrDefaultAsync(m => m.BoardId == id);
			if (board == null)
			{
				return NotFound();
			}

			return View(board);
		}

		// GET: Boards/Create
		[Authorize(Roles = "Admin")]
		public IActionResult Create()
		{
			return View();
		}

		// POST: Boards/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[Authorize(Roles = "Admin")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name,Length,Width,Thickness,Volume,Type,Price,Equipment,PicturePath")] Board board)
		{
			if (ModelState.IsValid)
			{
				_context.Add(board);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(board);
		}

		// GET: Boards/Edit/5
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Board == null)
			{
				return NotFound();
			}

			var board = await _context.Board.FindAsync(id);
			if (board == null)
			{
				return NotFound();
			}
			return View(board);
		}

		// POST: Boards/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[Authorize(Roles = "Admin")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int? id, byte[] rowVersion)
		{
			if (id == null)
			{
				return NotFound();
			}

			var BoardToUpdate = await _context.Board.FirstOrDefaultAsync(m => m.BoardId == id);

			if (BoardToUpdate == null)
			{
				Board BoardDepartment = new Board();
				await TryUpdateModelAsync(BoardDepartment);
				ModelState.AddModelError(string.Empty,
					"Unable to save changes. The department was deleted by another user.");
				return View(BoardDepartment);
			}

			_context.Entry(BoardToUpdate).Property("RowVersion").OriginalValue = rowVersion;

			if (await TryUpdateModelAsync<Board>(
				BoardToUpdate,
				"",
				s => s.Name, s => s.Length, s => s.Width, s => s.Thickness, s => s.Volume, s => s.Type, s => s.Price, s => s.RowVersion, s => s.Equipment, s => s.PicturePath, s => s.IsBooked))
			{
				try
				{
					await _context.SaveChangesAsync();
					return RedirectToAction(nameof(Index));
				}
				catch (DbUpdateConcurrencyException ex)
				{
					var exceptionEntry = ex.Entries.Single();
					var clientValues = (Board)exceptionEntry.Entity;
					var databaseEntry = exceptionEntry.GetDatabaseValues();
					if (databaseEntry == null)
					{
						ModelState.AddModelError(string.Empty,
							"Unable to save changes. The department was deleted by another user.");
					}
					else
					{
						var databaseValues = (Board)databaseEntry.ToObject();

						if (databaseValues.Name != clientValues.Name)
						{
							ModelState.AddModelError("Name", $"Current value: {databaseValues.Name}");
						}
						if (databaseValues.Length != clientValues.Length)
						{
							ModelState.AddModelError("Length", $"Current value: {databaseValues.Length}");
						}
						if (databaseValues.Width != clientValues.Width)
						{
							ModelState.AddModelError("Width", $"Current value: {databaseValues.Width}");
						}
						if (databaseValues.Thickness != clientValues.Thickness)
						{
							ModelState.AddModelError("Thickness", $"Current value: {databaseValues.Thickness}");
						}
						if (databaseValues.Volume != clientValues.Volume)
						{
							ModelState.AddModelError("Volume", $"Current value: {databaseValues.Volume}");
						}
						if (databaseValues.Type != clientValues.Type)
						{
							ModelState.AddModelError("Type", $"Current value: {databaseValues.Type}");
						}
						if (databaseValues.Price != clientValues.Price)
						{
							ModelState.AddModelError("Price", $"Current value: {databaseValues.Price}");
						}
						if (databaseValues.Equipment != clientValues.Equipment)
						{
							ModelState.AddModelError("Equipment", $"Current value: {databaseValues.Equipment}");
						}
						if (databaseValues.PicturePath != clientValues.PicturePath)
						{
							ModelState.AddModelError("PicturePath", $"Current value: {databaseValues.PicturePath}");
						}


						ModelState.AddModelError(string.Empty, "The record you attempted to edit "
								+ "was modified by another user after you got the original value. The "
								+ "edit operation was canceled and the current values in the database "
								+ "have been displayed. If you still want to edit this record, click "
								+ "the Save button again. Otherwise click the Back to List hyperlink.");
						BoardToUpdate.RowVersion = (byte[])databaseValues.RowVersion;
						ModelState.Remove("RowVersion");
					}
				}
			}
			return View(BoardToUpdate);
		}

		// GET: Boards/Delete/5
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Delete(int? id, bool? concurrencyError)
		{
			if (id == null || _context.Board == null)
			{
				return NotFound();
			}

			var surfboard = await _context.Board
				.AsNoTracking()
				.FirstOrDefaultAsync(m => m.BoardId == id);

			if (surfboard == null)
			{
				if (concurrencyError.GetValueOrDefault())
				{
					return RedirectToAction(nameof(Index));
				}
				return NotFound();
			}
			if (concurrencyError.GetValueOrDefault())
			{
				ViewData["ConcurrencyErrorMessage"] = "The record you attempted to delete "
					+ "was modified by another user after you got the original values. "
					+ "The delete operation was canceled and the current values in the "

SurfBoardWeb/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SurfBoardWeb.Data;
using SurfBoardWeb.Models;
using SurfBoardWeb.Models.ViewModels;
using static System.Net.WebRequestMethods;

namespace SurfBoardWeb.Controllers
{
	public class BookingsController : Controller
	{
		private readonly SurfBoardWebContext _context;
		private readonly UserManager<DefaultUser> _userManager;
		private readonly HttpClient _httpClient;
		private readonly RoleManager<IdentityRole> _roleManager;

		public BookingsController(SurfBoardWebContext context, UserManager<DefaultUser> userManager, HttpClient httpClient, RoleManager<IdentityRole> roleManager)
		{
			_context = context;
			_userManager = userManager;
			_httpClient = httpClient;
			_roleManager = roleManager;
		}

		// GET: Bookings
		public async Task<IActionResult> Index()
		{
			var surfBoardWebContext = _context.Bookings.Include(b => b.UserId);
			return View(await surfBoardWebContext.ToListAsync());
		}



		// GET: Bookings/Create
		public IActionResult Create(int id)
		{
			ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
			ViewData["BoardId"] = id;
			return View();
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("StartDate,EndDate,UserId,BoardId,email,phoneNumber")] BookingRequestVM booking) //Ændre alt til BookingRequestVM requestedVM
		{
			if (ModelState.IsValid)
			{
				var board = _context.Board.First(a => a.BoardId == booking.BoardId);
				if (board == null) { return BadRequest("boardet du booker findes ikke"); }
				if (User.Identity.Name == null)
				{
					#region CREATES SEUDO USER
					try
					{
						DefaultUser newUser = new DefaultUser();
						newUser.Email = booking.email;
						newUser.UserName = booking.email;
						newUser.PhoneNumber = booking.phoneNumber;
						var result = await _userManager.CreateAsync(newUser);

						if (result.Succeeded)
						{
							var roleName = "User";

							var role = await _roleManager.FindByNameAsync(roleName);
							if (role != null)
							{
								var addToRollR = await _userManager.AddToRoleAsync(newUser, roleName);

								if (!addToRollR.Succeeded)
								{
									foreach (var error in addToRollR.Errors)
									{
										ModelState.AddModelError(string.Empty, error.Description);
									}
									return BadRequest();
								}
							}
						}
						DefaultUser user = await _userManager.FindByEmailAsync(booking.email);
						booking.UserId = user.Id;

					}
					catch
					{
						return BadRequest("failed to save user info");
					}
                    #endregion

                    var response = await _httpClient.PostAsJsonAsync(@"https://localhost:7163/api/v1.0/Booking/Create", booking);
					bool returnValue = response.IsSuccessStatusCode;
					if(returnValue == false)
					{
						return BadRequest("You can only rent 1 board when you are not logged in");
					}
					
				}

				else
				{
					var user = _context.Users.FirstOrDefault(a=>a.UserName == User.Identity.Name);
					booking.UserId = user.Id;

					await _httpClient.PostAsJsonAsync(@"https://localhost:7163/api/v2.0/Booking/Create", booking);
				}

				//ændre board til at være booket
				var tempboard = _context.Board.First(a => a.BoardId == booking.BoardId);
				tempboard.IsBooked = true;
				_context.SaveChanges();

				return Redirect("/Boards");
			}

			return BadRequest(ModelState);
		}



		// GET: Bookings/Delete/5
		public async Task<IActionResult> Delete(int? id, bool? concurrencyError)
		{
			if (id == null || _context.Bookings == null)
			{
				return NotFound();
			}

			var booking = await _context.Bookings
				.AsNoTracking()
				.FirstOrDefaultAsync(m => m.BookingsId == id);

			if (booking == null)
			{
				if (concurrencyError.GetValueOrDefault())
				{
					return RedirectToAction(nameof(Index));
				}
				return NotFound();
			}
			if (concurrencyError.GetValueOrDefault())
			{
				ViewData["ConcurrencyErrorMessage"] = "The record you attempted to delete " + "was modified by another user after you got the original values. "
					+ "The delete operation was canceled and the current values in the " + "database have been displayed. If you still want to delete this "
					+ "record, click the Delete button again. Otherwise " + "click the Back to List hyperlink.";
			}

			return View(booking);
		}

		// POST: Bookings/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Bookings == null)
			{
				return Problem("Entity set 'Bookings'  is null.");
			}
			var booking = await _context.Bookings.FindAsync(id);
			if (booking != null)
			{
				var board = _context.Board.First(a => a.BoardId == booking.BoardId);
				board.IsBooked = false;
				_context.Bookings.Remove(booking);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool BookingsExists(int id)
		{
			return _context.Bookings.Any(e => e.BookingsId == id);
		}
	}
}

SurfBoardWeb/Views/Boards/Create.cshtml
@model SurfBoardWeb.Models.Board

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Board</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label required"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Length" class="control-label required"></label>
                <input asp-for="Length" class="form-control" />
                <span asp-validation-for="Length" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width" class="control-label required"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thickness" class="control-label required"></label>
                <input asp-for="Thickness" class="form-control" />
                <span asp-validation-for="Thickness" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Volume" class="control-label required"></label>
                <input asp-for="Volume" class="form-control" />
                <span asp-validation-for="Volume" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label required"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label required"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Equipment" class="control-label"></label>
                <input asp-for="Equipment" class="form-control" />
                <span asp-validation-for="Equipment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PicturePath" class="control-label"></label>
                <input asp-for="PicturePath" class="form-control" />
                <span asp-validation-for="PicturePath" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SurfBoardWeb/Views/Boards/Details.cshtml
@model SurfBoardWeb.Models.Board

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Board</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Length)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Length)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Width)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thickness)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thickness)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Volume)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Volume)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Equipment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Equipment)
        </dd>
        
    </dl>
</div>
<img src="@Html.DisplayFor(model=> model.PicturePath)" height="500"/>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.BoardId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SurfBoardWeb/Views/Boards/Index.cshtml
@model PaginatedList<SurfBoardWeb.Models.Board>
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@{
	ViewData["Title"] = "Index";
}

<h1>Index</h1>
@if (User.IsInRole("Admin"))
{
	<p>
		<a asp-action="Create">Create New</a>
	</p>
}
<form asp-controller="Boards" asp-action="Index" method="get">
	<p>
		Find by name: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
		<input type="submit" value="Søg" class="btn btn-default" /> |
		<a asp-action="Index">Stop Søgning</a>
	</p>
</form>

<table class="table">
	<thead>
		<tr>
			<th>
				<a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Name</a>
			</th>
			<th>
				<a asp-action="Index" asp-route-sortOrder="@ViewData["LengthSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Length</a>
			</th>
			<th>
				<a asp-action="Index" asp-route-sortOrder="@ViewData["WidthSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Width</a>
			</th>
			<th>
				<a asp-action="Index" asp-route-sortOrder="@ViewData["ThicknessSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Thickness</a>
			</th>
			<th>
				<a asp-action="Index" asp-route-sortOrder="@ViewData["VolumeSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Volume</a>
			</th>
			<th>
				<a asp-action="Index" asp-route-sortOrder="@ViewData["TypeSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Type</a>
			</th>
			<th>
				<a asp-action="Index" asp-route-sortOrder="@ViewData["PriceSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Price</a>
			</th>
			<th>
				<a asp-action="Index" asp-route-sortOrder="@ViewData["EquipmentSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Equipment</a>
			</th>
			<th>
				billede
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{

			@if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("PremiumUser")))
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.Name)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Length)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Width)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Thickness)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Volume)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Type)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Price)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Equipment)
					</td>
					<td>
						<img src="@Html.DisplayFor(modelItem => item.PicturePath)" height="40" class="hoverImage">
					</td>
					@if (User.IsInRole("Admin"))
					{
						<td>
							<a asp-action="Edit" asp-route-id="@item.BoardId">Edit</a> |
							<a asp-action="Details" asp-route-id="@item.BoardId">Details</a> |
							<a asp-action="Delete" asp-route-id="@item.BoardId">Delete</a>
						</td>
					}
					else if (item.IsBooked == false)
					{
						<td>
							<a asp-controller="Bookings" asp-route-id="@item.BoardId" asp-action="Create">Book board</a>
						</td>
					}
				</tr>
			}
			else if (!User.Identity.IsAuthenticated && item.BoardId % 2 == 0)
			{
				if (item.IsBooked == false)
				{

					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.Name)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Length)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Width)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Thickness)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Volume)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Type)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Price)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Equipment)
						</td>
						<td>
							<img src="@Html.DisplayFor(modelItem => item.PicturePath)" height="40" class="hoverImage">
						</td>
						@if (User.IsInRole("Admin"))
						{
							<td>
								<a asp-action="Edit" asp-route-id="@item.BoardId">Edit</a> |
								<a asp-action="Details" asp-route-id="@item.BoardId">Details</a> |
								<a asp-action="Delete" asp-route-id="@item.BoardId">Delete</a>
							</td>
						}
						else
						{
							@*lav if hvis board er booked, ik hvis*@
							<td>
								<a asp-controller="Bookings" asp-route-id="@item.BoardId" asp-action="Create">Book board</a>
							</td>
						}
					</tr>
				}
			}

		}
	</tbody>
</table>
@{
	var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
	var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
	Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
	Next
</a>